version: '3.8'

# Dịch vụ (container) sẽ được tạo ra
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_SA_PASSWORD} -Q \"SELECT 1\""]
      interval: 20s
      timeout: 10s
      retries: 30
      start_period: 60s

  webapp:
    image: electronic-shop-webapp
    container_name: electronic-shop-webapp
    build: .
    ports:
      - "8080:5000"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ElectronicShopDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True
    depends_on:
      db:
        condition: service_healthy

volumes:
  sql-data:
    driver: local

